### ISSUE TITLE
Does WER plugin enable content-script hot reload?

### ISSUE THREAD

**Issue by awardx** [rubenspgcavalcante/webpack-extension-reloader#10]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [X] question

**Environment:**
  - OS: Win
  - Library Version: 

**I'm going to open a PR:**
  - [ ] yes
  - [X] no

**Description:**
[I stumbled upon Kocal Vue extension boilerplate which is using webpack-chrome-extension-reloader plugin, but they say that it only supports hot reloading module for background scripts.

When I read the documentation for WER plugin, I have an impression that this plugin does support Hot Module Reloading for content-scripts too.

I tested the boilerplate with WCER plugin installed, and indeed, it seems that plugin only reloads background script entries. Unfortunately, for the content script changes, I have to reload both - extension and browser tab. 

Could it be that the boilerplate mentioned above is not set up correctly and therefore not supporting the HRM for content scripts? Or am I missing something from your docs? ]

**Comment by rubenspgcavalcante** [comment]
Hey @awardx , I think it's a bug on the transition from Chrome extension API to the standard one. I need to check what's happening exactly 🤔

**Comment by rubenspgcavalcante** [comment]
Can you check it again, the PR made for #5 may have fixed this issue

**Comment by awardx** [comment]
@rubenspgcavalcante turns out Kocal plugin template is using old WCER (0.8.3). I updated the version to 1.3.0 before running npm run and now it works. 

My concern was that they have explicitly stated in the documentation - ⚠️ Keep in mind that HMR only works for your background entry, - therefore wanted to confirm that with you. I'll propose them to update their docs and some code.

Thanks for your support.
