### ISSUE TITLE
Reloading open default popup

### ISSUE THREAD

**Issue by just-jeb** [rubenspgcavalcante/webpack-extension-reloader#22]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Description:**
Is there a way to make an open default popup reload on change? Thanks.

**Comment by rubenspgcavalcante** [comment]
Hey @just-jeb unfortunately not yet,
Still a limitation on the extension SDK side, you need to click on it again to see the changes there :(
