### ISSUE TITLE
error when background is a page rather than script

### ISSUE THREAD

**Issue by kinghat** [rubenspgcavalcante/webpack-extension-reloader#33]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: KDE Neon
  - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
  - Library Version: 1.1.0

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
i think there is an error when pointing to the manifest and using `background` as a page and not a script like so:
```
new ExtensionReloader({
        manifest: path.resolve(__dirname, "src/manifest.json"),
      }),
```
```
	"background": {
		"page": "background/background.html"
	},
```

>  ERROR  TypeError: Cannot read property 'some' of undefined

**Comment by saveroo** [comment]
same issue

**Comment by Nisthar** [comment]
Same issue here

**Comment by cryptrustowner** [comment]
Same issue, please we need answer.

**Comment by rubenspgcavalcante** [comment]
Hey there, at least one background script is required to make the reload work.
I'll add a extra check to point to this requirement
