### ISSUE TITLE
Hot reload devtools extension

### ISSUE THREAD

**Issue by JelleRoets-Oqton** [rubenspgcavalcante/webpack-extension-reloader#35]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: any
  - Browser: chrome
  - Library Version:

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
I’m currently building a chrome devtools extension (https://developer.chrome.com/extensions/devtools). Unfortunately this plugin doesn’t automatically reload the custom devtools page, although it does reload the background script.
What would it take to extend your extension, in order to hot reload devtools extensions as well?

**Comment by r0kan** [comment]
+1

**Comment by rubenspgcavalcante** [comment]
Not sure, this is specific from Chrome right?
If isn't on the oficial [browser extension specification](https://browserext.github.io/browserext/) unfortunately can't do anything.
If I add something like this (that I even know if is possible) I'll be dropping all other browsers :/

Sorry about that and thanks for the feedback!
