### ISSUE TITLE
Be aware of extension CSP and modify manifest.json content_security_policy attribute

### ISSUE THREAD

**Issue by bershanskiy** [rubenspgcavalcante/webpack-extension-reloader#39]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS:
  - Browser:
  - Library Version:

**I'm going to open a PR:**
  - [x] yes
  - [ ] no

**Description:**
_Background_
I develop an extension with a strict Content Security Policy (specified in the manifest as `content_security_policy`) that restricts network communication. Of curse, I want my production CSP to restrict WebSocket communication even to localhost. At the same time, I want to use this plugin in development. I don't want to add extra logic to my build scripts and instead, I'd like this plugin to edit manifest when it needs to.

_Desired behavior_
When the plugin is active, it works seamlessly no matter what CSP was in the source manifest. That is, the plugin automatically relaxes CSP as it needs to.

_Current behavior_
Connection refused because it is restricted by CSP. E.g., if CSP includes directive `connect-src https://*`, I get the following error:
```
Refused to connect to 'ws://localhost:9090/' because it violates the following Content Security Policy directive: "connect-src https://*".
```

_How to fix it_
I think the plugin can modify the CSP before it's written to the output to allow communication with `WSHost` from the script. Note that it's insufficient to just append a directive like `connect-src <wsHost>` because duplicate directives do not relax earlier directives. The script would need to extract `connect-src` and/or `default-src` and append `wsHost` to them and then assemble the whole CSP back (easily done with reg ex).

_Test case_
I'll post reduced test case (a tiny extension project) if you are interested in this issue.

**Comment by bershanskiy** [comment]
_Test case_

Build with `npm run build`. As is, CSP contains directive `connect-src ws://localhost:*/` so everything builds without errors. To see the issue, remove `ws://localhost:*/`.

[testcase.zip](https://github.com/rubenspgcavalcante/webpack-extension-reloader/files/3526435/testcase.zip)

**Comment by ElForastero** [comment]
I could implement this if someone will give advice on where this functionality should be present in the plugin. It's not clear to me after reading the sources.

**Comment by bershanskiy** [comment]
@ElForastero If you need an immediate fix for your own project, I'd recommend not expecting this to be fixed any time soon and manually writing the `manifest.json` for dev and prod builds.

The real issue here is not the difficulty of writing a patch and making a PR, but actually getting it merged upstream (here). As per [`.github/CONTRIBUTING.md`](https://github.com/rubenspgcavalcante/webpack-extension-reloader/blob/master/.github/CONTRIBUTING.MD):
> Before create any pull requests, please open a issue explaining the situation

Since @rubenspgcavalcante hasn't responded yet, I'm not sure he is even interested in this fix (which I totally understand, since any extra code inevitably increases complexity and actually takes more time to maintain over time than to write it initially).

**Comment by rhaksw** [comment]
> I don't want to add extra logic to my build scripts

I did this in my extension using a solution I found [on SO](https://stackoverflow.com/a/54700817/2636364), it's not too bad. Basically,
```
plugins: [
    new CopyWebpackPlugin([
    {
      from: "./src/manifest.json",
      to:   "./manifest.json",
      // from https://stackoverflow.com/a/54700817/2636364
      transform (content, path) {
        if (mode !== "development") {
          return content
        } else {
          return modify(content)
        }
      }
    }])
...
]
```
Then, `modify()` can be something like,

```
function modify(buffer) {
  var manifest = JSON.parse(buffer.toString());
  manifest.permissions.push("http://localhost/*")
  manifest.content_scripts[0].matches.push("http://localhost/*")
  if (process.env.FORFIREFOXDEV) {
    manifest.browser_specific_settings = {
      "gecko": {
        "id": "example@example.com"
      }
    }
  }
  // pretty print to JSON with two spaces
  return JSON.stringify(manifest, null, 2);
}
```

I broke the manifest creation out into a [separate step](https://github.com/revddit/revddit-language-fix/blob/master/build-manifest.webpack.config.js) that completes before webpack-extension-reloader and the rest of my project build, however it could be done in the same step so long as webpack-extension-reloader does not depend upon the changes you're making, or you're not using the `manifest` option for webpack-extension-reloader.

**Comment by bershanskiy** [comment]
@rhaksw Yes, I'm pretty much just doing that (programmatically edit the manifest).
Also, there is a small bug in your example `modify` function: since we are talking about CSP, we need to edit `content_security_policy` key and not `permissions` key. But the idea is the same.

> I broke the manifest creation out into a separate step t

I simply made a manifest reader and writer with `fs` and `JSON` that patches the manifest before config export. The exact order of execution does not really matter here, because this plugin does not rebuild on manifest change; if it did, we would need to watch out for infinite loops of rebuild -> config generation -> manifest write -> rebuild -> ...

**Comment by rhaksw** [comment]
Yes I just meant the above as an example. Glad to hear you already have a working solution =)

**Comment by rubenspgcavalcante** [comment]
Hi, thanks for the feedback and sorry for the delay, it has been a tough year for me :/
So, this plugin doesn't outputs the `manifest.json` (at maximum reads it to get useful info about your extension). So, what can be done? The answer is pretty simple and is a trick I always use on all plugins on webpack projects, use your NODE_ENV :D

It's similar to what @rhaksw said, but no programming involved. Create two versions of the manifest, one for dev other for prod and choose it depending on the environment

```js
    new CopyWebpackPlugin([
      {
        /***********************************************************************/
        /* If you have different configurations for development and production,*/
        /* you can have two manifests (one for each environment)               */
        /***********************************************************************/
        from:
          process.env.NODE_ENV === "development"
            ? "./sample/manifest.dev.json"
            : "./sample/manifest.prod.json",
        to: "manifest.json"
      },
    ])
```
This way you can set all different configurations on your need for both dev and prod :)
I'm opening a PR and adding this to the sample code right now
