### ISSUE TITLE
Is it possible to reload when manifest.json changes?

### ISSUE THREAD

**Issue by rhaksw** [rubenspgcavalcante/webpack-extension-reloader#41]
**Type:**
  - [ ] bug
  - [ ] feature
  - [x] enhancement
  - [ ] question

**Environment:**
  - OS: Ubuntu 19.04
  - Browser: Chrome
  - Library Version: v1.1.1

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**

Would it be possible to make it so that changes to `manifest.json` also cause a reload? I noticed that it does not reload when I only make changes to the manifest. If I make changes to the manifest and then some other code, everything updates and the new manifest's changes are incorporated.

This package is great. Thank you for making it!

By the way, in case anyone finds it useful, I made an enhancement to my workflow as part of [another extension project](https://github.com/revddit/revddit-language-fix) that allows `manifest.json` to be variable, for example including a `http://localhost/*` permission conditionally when developing extensions alongside a website. And, since `webpack-extension-reloader` requires manifest.json to exist before running webpack, I broke out the manifest build into a new step that runs [before the rest of the build](https://github.com/revddit/revddit-language-fix/blob/master/build-manifest.webpack.config.js).

**Comment by rubenspgcavalcante** [comment]
No, as the information from the manifest.json is read at the start, as a common file and using the manifest to inform about the content/bg scripts is optional, as you can pass as options to the plugin.
As you can see this plugin don't parses the manifest.json, only read it, on the compilation time (that's why you use it alongside copy-webpack-plugin).
Also added to the docs a way to use multiple manifests.json, depending on your environment (dev or prod). It's a very simple trick that can be used on all plugins on webpack :)

**Comment by rhaksw** [comment]
During extension development I tend to add/remove things from the manifest while I discover what permissions are needed etc. It would be useful to have a mechanism that auto-copies the manifest in the event of such changes, and afterwards auto-reloads the extension in the browser.

Also, regarding dev/prod versions of the manifest, it is easier to maintain one 'base' manifest and modify that on the fly with a script than maintain separate copies. There are more cases than just dev/prod, for example, Firefox requires a manifest key when using `storage.sync`,

> Note that the implementation of storage.sync in Firefox relies on the Add-on ID. If you use `storage.sync`, you must set an ID for your extension using the ~~applications~~ `browser_specific_settings` manifest.json key.

Chrome does not support this key and will tell you your manifest is malformed if you include it.

And there are certain browser-specific things that don't look they'll be standardized anytime soon, for example,

* Chrome's plans to stop supporting the webRequest API (Firefox has not said they will drop the API, nor have they committed to keeping it)
* Chrome's use of CORB, which prevents content scripts from making cross origin requests (Firefox still allows cross origin requests from content scripts)

These differences may impact what appears in your manifest, so you could potentially have Firefox-dev, Firefox-prod, Chrome-dev, Chrome-prod, etc.
