### ISSUE TITLE
Unable to find manifest.json on subdirectories

### ISSUE THREAD

**Issue by rhaksw** [rubenspgcavalcante/webpack-extension-reloader#43]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Ubuntu 19.04
  - Browser: Chrome
  - Library Version: v1.1.1

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
When using the `manifest` parameter to ExtensionReloader, [this block of code](https://github.com/rubenspgcavalcante/webpack-extension-reloader/blob/master/src/utils/manifest.ts#L31) essentially requires that you place your background script in the folder alongside `manifest.json`. An error occurs if you put your background script in a subfolder such as `src/background.js`.

The `toRemove` variable seems setup to expect a value like `.js`, but if you have a subfolder, it can end up as `./src/.js`. A fix might be to break the `toRemove` variable into two parts, `toRemove_prefix` and `toRemove_suffix`, resulting in `./src/` and `.js`.

As I look at this more, I wonder why content scripts, background scripts and extension pages need to be specified separately for webpack-extension-reloader.

**Comment by rubenspgcavalcante** [comment]
Humm interesting, nice catch :)
I'll take a look, thanks for making the check on the code!

**Comment by rubenspgcavalcante** [comment]
I think there was a misunderstanding, the manifest.json should point to the final file path not to the source files.
I've just made some tests, making the background script, from the sample, output the background inside a `bg/` under the dist. Worked as expected.
I'll be closing this for now
