### ISSUE TITLE
Unable to develop webpack-extension-reloader on Windows

### ISSUE THREAD

**Issue by Aidurber** [rubenspgcavalcante/webpack-extension-reloader#45]
**Type:**
  - [X] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows
  - Browser: N/A
  - Library Version: 1.1.1

**I'm going to open a PR:**
  - [X] yes
  - [ ] no

**Description:**
The npm scripts commands `NODE_ENV` setting is incompatible with Windows. We need to use cross-env easily allow non-Unix based devs to modify webpack extension reloader.

**Comment by rubenspgcavalcante** [comment]
Hi, I think isn't necessary to set it directly to package.json as you can run by:
`npx cross-env yarn build`

This will have the same effect and a unnecessary proxy added for Linux and Mac users :/

**Comment by Aidurber** [comment]
That's fair, thanks for explaining @rubenspgcavalcante
