### ISSUE TITLE
syntax bug in 1.1.3

### ISSUE THREAD

**Issue by kinghat** [rubenspgcavalcante/webpack-extension-reloader#55]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Linux KDE Neon
  - Browser: Firefox Developer 71.0b9 (64-bit)
  - Library Version: webpack-extension-reloader: 1.1.3

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
latest update produces an error on run:

![image](https://user-images.githubusercontent.com/16073360/68797327-03bf3380-061a-11ea-8fb9-80d0cfce61f7.png)

this is the code in question with the error in `/dist`:
```
//# sourceMappingURL=browser-polyfill.js.map
"";
}).bind(injectionContext)();
var browser = injectionContext.browser;
var signals = JSON.parse("{"SIGN_CHANGE":"SIGN_CHANGE","SIGN_RELOAD":"SIGN_RELOAD","SIGN_RELOADED":"SIGN_RELOADED","SIGN_LOG":"SIGN_LOG","SIGN_CONNECT":"SIGN_CONNECT"}");
var config = JSON.parse("{"RECONNECT_INTERVAL":2000,"SOCKET_ERR_CODE_REF":"https://tools.ietf.org/html/rfc6455#section-7.4.1"}");
var reloadPage = "true" === "true";
var wsHost = "ws://localhost:9090";
```

not sure if this is a conflict with `webextension-polyfill`? reverting back to 1.1.2 works fine.

**Comment by ErikAGriffin** [comment]
I'm also getting this issue.  Based on the output it looks like maybe this line 16 in src/middleware/wer-middleware.raw.ts may be the culprit:
```javascript
const signals: any = JSON.parse("<%= signals %>");
```
if you look at the above output `var signals = JSON.parse("{"SIGN_CHANGE":"SIGN_CHANGE","SIGN_RELOAD":"SIGN_RELOAD","SIGN_RELOADED":"SIGN_RELOADED","SIGN_LOG":"SIGN_LOG","SIGN_CONNECT":"SIGN_CONNECT"}");` the double quotes immediately cancel each other out.  Changing the above to:
```
const signals: any = JSON.parse('<%= signals %>');
```
may solve the issue

**Comment by rubenspgcavalcante** [comment]
Humm, this may be work from prettier or ts-lint automatically changing based on the quotes rules.
I'll fix and make sure both don't change it 👍
