### ISSUE TITLE
[Feature] Possibility to use HMR on content-script

### ISSUE THREAD

**Issue by Gramatiik** [rubenspgcavalcante/webpack-extension-reloader#6]
**Type:**
  - [ ] bug
  - [x] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: macOS
  - Library Version: 1.0.0

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
Hello,

After reading the README I had a few more questions. If I understand well, this plugin allows reloading the chrome extension from its background script and reloading a page where a content script was injected.

But is it also possible to perform **Hot Module Replacement** with it?

My use case is the following:
- A chrome extension which only overrides the "new tab" page.
- I want to use HMR on this page for development purposes.
- If I use **webpack-dev-server** I get HMR but I don't have the chrome extension APIs available.
- If I use the extension, then it's the opposite!

Any idea on how to achieve this (or if it's even possible...).

Thank you :)

**Comment by rubenspgcavalcante** [comment]
Hey @Gramatiik ,
Currently, it only supports hot-reloading, hot-module-reloading is something more complex. In fact, I need to check the limitations of injecting scripts at runtime without running the extension API reload (or the tab reload on the case of content-scripts)
Maybe specific for content scripts, but still, need to check that.

I'll let this issue open and change it to match a feature request, ok?

**Comment by Gramatiik** [comment]
Hello @rubenspgcavalcante !

Thanks for investigating on this, is it possible to state somewhere in the README that HMR **isn't supported** at the moment ?

Anyways thanks for your work :)

**Comment by rubenspgcavalcante** [comment]
Humm I think it needs to be another issue, it relates to docs 🤔

**Comment by Gramatiik** [comment]
I could create another issue for that, and even a PR 😄
